openapi: "3.0.2"
info:
  title: "Love Republic API"
  version: "1.0.1"
  description: Product Feedback API

servers:
- url: https://test.ru
  description: Test server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 

 
paths:
  /app/feedback:
    get:
      summary: Запрос на проверку триггера показа ОС и получение параметров для формы ОС
      responses:
        200:
          description: Успешный ответ с данными для главной страницы приложения
          content:
            application/json:
              schema:
                $ref: "models.yaml#/components/schemas/FeedbackResponse"
    post:
      summary: Submit product feedback
      description: Submit a new product feedback entry
      requestBody:
        description: "Тело запроса"
        content:
          application/json:
            schema:
              $ref: "models.yaml#/components/schemas/FeedbackRequest"
      responses:
        200:
          description: Feedback submitted successfully
        400:
          description: Invalid request
        500:
          description: Internal server error