openapi: "3.0.2"
info:
  title: "Feedback BK API"
  version: "1.0.1"
  description: Product Feedback API

servers:
- url: https://test.ru
  description: Test server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 

 
paths:
  /app/feedback:
    get:
      summary: Запрос на проверку триггера показа ОС и получение параметров для формы ОС
      responses:
        200:
          description: Успешный ответ с данными для главной страницы приложения
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedbackResponse"
    post:
      summary: Submit product feedback
      description: Submit a new product feedback entry
      requestBody:
        description: "Тело запроса"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedbackRequest"
      responses:
        200:
          description: Feedback submitted successfully
        400:
          description: Invalid request
        500:
          description: Internal server error
    
  /app/feedback/list:
    get:
      summary: Запрос на получение триггеров по всем заказам
      responses:
        200:
          description: Успешный ответ с данными по каждому заказу
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedbackRequest"

  components:
    schemas: 
      FeedbackResponse:
        type: object
        properties:
          feedbackTrigger:
            type: boolean
            required: true
            example: true
          orderId:
            nullable: true
            type: integer
            example: 4
          dishes:
            type: array
            nullable: true
            items:
              $ref: "models.yaml#/components/schemas/Dish"
          feedbackParameters:
            type: array
            items:
              $ref: "models.yaml#/components/schemas/FeedbackParameter"
      
      Dish: 
        type: object
        properties:
          dishId:
            type: integer
            example: 4
          dichCode:
            description: код продукта для аналитики, можем сразу не понадобиться, на развитие
            type: integer
          dishImageURL:
            type: string
            example: https://i.insider.com/602ee9d81a89f20019a377c6?width=1136&format=jpeg
            description: only file name 
          dishName:
            type: string
            example: Воппер Джуниор

      FeedbackParameter: 
        type: object
        properties:
          parameterId:
            type: integer
            example: 4
          parameterName:
            type: string
            example: Температура
          parameterType:
            type: string
            description: >
              Тип вопроса:
              string - Свободный ответ
              integer - Оценка от 0 до 5
              boolean - Вопрос с вариантом ответа да/нет
            enum: [string, integer, boolean]
            example: string
      
  |// добавить параметра для явного обозначения feedback: false

      FeedbackRequest: 
        type: object
        description:  ОС от гостя по всему заказу
        properties:
          orderId:
            type: integer
            example: 4
          feedbackByProducts:
            type: array
            items:
              $ref:  "models.yaml#/components/schemas/FeedbackByProduct"
      
      FeedbackByProduct:
        type: object
        description:  ОС от гостя по одному продукту
        properties:
          dishId:
            type: integer
            example: 4
          dishCode:
            type: integer
            example: 4
          parameters:
            type: array
            items:
              $ref:  "models.yaml#/components/schemas/FeedbackParameterResult"
      \
      FeedbackParameterResponse: 
        oneOf:
          -  "models.yaml#/components/schemas/StringResult"
          -  "models.yaml#/components/schemas/IntegerResult"
          -  "models.yaml#/components/schemas/BoolResult"
        
      StringResult:
        type: object
        properties:
          parameterId:
            type: integer
            example: 4
          parametersResult:
            type: string
            example: Холодная картошка

      IntegerResult:
        type: object
        properties:
          parameterId:
            type: integer
            example: 2
          parametersResult:
            type: integer
            example: 1
      
      BoolResult:
        type: object
        properties:
          parameterId:
            type: integer
            example: 4
          parametersResult:
            type: boolean
            example: true