openapi: "3.0.2"
info:
  title: "Love Republic API"
  version: "1.0.1"
  description: Документ содержит описание API электронных подарочных сертификатов в приложении "Love Republic"

servers:
- url: https://apitest.loverepublic.ru
  description: Test server

paths:
  /app/feedback:
    get:
      summary: Запрос на проверку необходимости показать форму ОС, если да, то в ответе прислать параметры для ОС
      responses:
        200:
          description: Успешный ответ с данными для показа формы ОС
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedbackResponse"
        404:
          description: Заказы с фидбэком отсутствуют / Нет заказов
  
  /app/feedback/product:
    post:
      summary: Запрос на отправку ОС 
      requestBody:
        description: "Тело запроса"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedbackRequest"
      responses:
        200:
          description: Feedback submitted successfully
        400:
          description: Invalid request
        500:
          description: Internal server error
    
  /app/feedback/list:
    get:
      summary: Запрос на получение списка заказов с необходимостью показать форму ОС
      responses:
        200:
          description: Успешный ответ с данными по каждому заказу
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedbackListResponse"
        404:
          description: Заказы с фидбэком отсутствуют / Нет заказов

components:
  schemas: 
    FeedbackResponse:
      type: object
      properties:
        feedbackTrigger:
          type: boolean
          example: true
        orderId:
          nullable: true
          type: integer
          example: 4
        dishes:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Dish"
        feedbackParameters:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/FeedbackParameter"
      required: 
        - feedbackTrigger
    
    Dish: 
      type: object
      properties:
        dishId:
          type: integer
          example: 4
        dishCode:
          description: код продукта для аналитики, можем сразу не понадобиться, на развитие
          type: integer
        dishImageURL:
          type: string
          example: cheeseburger.jpg
          description: only file name 
        dishName:
          type: string
          example: Воппер Джуниор

    FeedbackParameter: 
      type: object
      properties:
        parameterId:
          type: integer
          example: 4
        parameterName:
          type: string
          example: Температура
        parameterType:
          type: string
          description: >
            Тип вопроса:
            string - Свободный ответ
            integer - Оценка от 0 до 5
            boolean - Вопрос с вариантом ответа да/нет
          enum: [string, integer, boolean]
          example: string
    

    FeedbackRequest: 
      type: object
      description:  ОС от гостя по всему заказу
      properties:
        feedbackTrigger:
          type: boolean
          example: true
        orderId:
          type: integer
          example: 4
        feedbackByProducts:
          type: array
          items:
            $ref:  "#/components/schemas/FeedbackByProduct"
      required: 
      - feedbackTrigger
    
    FeedbackByProduct:
      type: object
      description:  ОС от гостя по одному продукту
      properties:
        dishId:
          type: integer
          example: 4
        dishCode:
          type: integer
          example: 4
        parameters:
          type: array
          items:
            $ref:  "#/components/schemas/FeedbackParameterResult"
    
    FeedbackParameterResult: 
      oneOf:
        - $ref: "#/components/schemas/StringResult"
        - $ref: "#/components/schemas/IntegerResult"
        - $ref: "#/components/schemas/BoolResult"
      
    StringResult:
      type: object
      properties:
        parameterId:
          type: integer
          example: 4
        parametersResult:
          type: string
          example: Холодная картошка

    IntegerResult:
      type: object
      properties:
        parameterId:
          type: integer
          example: 2
        parametersResult:
          type: integer
          example: 1
    
    BoolResult:
      type: object
      properties:
        parameterId:
          type: integer
          example: 4
        parametersResult:
          type: boolean
          example: true
          
    FeedbackListResponse:
0
2
3
4
5
6
7
8
